### ISSUE TITLE
What version of pytorch you use

### ISSUE THREAD

**Issue by ghost** [antecessor/Wavenet#1]
I got error.
`RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)``
in forward
`--> 122         x=self.liner(x)
    123         return self.softmax(x)`
i try your example from jupyter

at the beginning it was error
`RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor`
when i change to
`device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
`
if use CPU
got 
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (8x4 and 5x11)`

**Comment by antecessor** [comment]
Hi.
See the last commit. I applied last commit because it worked for me, but based on your input size it may not fit to your case. So please fetch the code before last commit and try again with CPU.
